### ISSUE TITLE
Is this something you want to merge?

### ISSUE THREAD

**Issue by ghutchis** [brhr-iwao/libavogadro1cp2k#3]
We will likely make one additional release of Avogadro 1.3 this summer. Is this something you'd like to see contributed? If so, I'd be willing to work with you on making it available in the main distribution.

**Comment by brhr-iwao** [comment]
Professor Geoff,
Thank you so much for your offer. I am honored that libavogadro1cp2k will be merged into the Avogadro main distribution.
I am sorry that failed to update. I would be very happy if you could tell me what to improve.
