### ISSUE TITLE
Pasting cp2kextension.dll doest not creat psf/pot extension

### ISSUE THREAD

**Issue by raghavven** [brhr-iwao/libavogadro1cp2k#4]
Dear Friends,

I tried pasting the cp2kextension.dll file in the location C:\Program Files (x86)\Avogadro\lib\avogadro\1_2\extensions , but it did not add the psf/pot in the avogadro's extension menu.

Kindly advice. 

Thank you.

**Comment by brhr-iwao** [comment]
Thank you for trying the cp2k extension. Did the "CP2K" menu appear in the Avogadro's extensions menu?

**Comment by raghavven** [comment]
Thank you for your kind response. CP2K did not appear in the extension s menu.

**Comment by brhr-iwao** [comment]
Could you make sure that you put cp2kextension.dll from For_Avogadro120 (not For_Avogadro111) folder contained in unzipped cp2kextention.zip?

**Comment by raghavven** [comment]
Dear sir,

Thank you for your kind help. The 'extensions menu' now shows psf/pot and CP2K.
